import argparse
import pandas as pd
import numpy as np

def compare_outputs(original_path, new_path, tolerance, rel_tolerance=0.0):
    # Load the datasets
    print(f"Loading original file: {original_path}")
    if original_path.lower().endswith(('.xlsx', '.xls')):
        df_orig = pd.read_excel(original_path)
    else:
        df_orig = pd.read_csv(original_path)
        
    print(f"Loading new output file: {new_path}")
    df_new = pd.read_csv(new_path)

    # Standardize the file name column (handles "file", "File name", "File_Name", etc.)
    orig_file_col = next((col for col in df_orig.columns if col.lower() in ['file', 'file name', 'file_name']), df_orig.columns[0])
    new_file_col = next((col for col in df_new.columns if col.lower() in ['file', 'file name', 'file_name']), df_new.columns[0])

    # Merge the two dataframes on the filename
    merged = pd.merge(df_orig, df_new, left_on=orig_file_col, right_on=new_file_col, suffixes=('_orig', '_new'))

    if merged.empty:
        print("Error: No matching file names found between the two datasets. Check your file name formatting.")
        return

    # Identify matching columns to compare
    cols_orig = set(df_orig.columns) - {orig_file_col}
    cols_new = set(df_new.columns) - {new_file_col}
    common_cols = cols_orig.intersection(cols_new)

    print(f"\n--- Comparing {len(common_cols)} common columns across {len(merged)} matching files ---\n")

    results = []

    for col in sorted(common_cols):
        # Convert columns to numeric, coercing strings/errors to NaN
        s_orig = pd.to_numeric(merged[f"{col}_orig"], errors='coerce')
        s_new = pd.to_numeric(merged[f"{col}_new"], errors='coerce')

        # Drop NaNs to ensure we only compare valid numbers
        valid_mask = s_orig.notna() & s_new.notna()
        s_orig_valid = s_orig[valid_mask]
        s_new_valid = s_new[valid_mask]

        n_comparisons = len(s_orig_valid)

        # Skip column if no numeric data matches
        if n_comparisons == 0:
            continue

        # Calculate error metrics
        diff = np.abs(s_orig_valid - s_new_valid)
        mae = np.mean(diff)
        max_diff = np.max(diff)
        # Median relative error is scale-fair: a 0.3 Hz miss on an 80 Hz F0 and
        # on a 3400 Hz formant are judged on the same footing.
        rel = diff / np.abs(s_orig_valid).clip(lower=1e-9)
        median_rel_pct = np.median(rel) * 100

        # A value passes if it is within the absolute tolerance OR within the
        # relative tolerance of the reference (numpy.isclose semantics:
        # |a-b| <= atol + rtol*|b|). Relative tolerance is the meaningful knob
        # for a table whose columns span ~80 Hz (F0) to ~8000 Hz (Q75).
        within = diff <= (tolerance + rel_tolerance * np.abs(s_orig_valid))
        precision_pct = (np.sum(within) / n_comparisons) * 100

        label = (f"Accuracy (atol<={tolerance}, rtol<={rel_tolerance:g})"
                 if rel_tolerance else f"Accuracy (tol<={tolerance})")
        results.append({
            "Column": col,
            "Count": n_comparisons,
            "Mean_Abs_Error": f"{mae:.4f}",
            "Max_Difference": f"{max_diff:.4f}",
            "Median_Rel_Err": f"{median_rel_pct:.3f}%",
            label: f"{precision_pct:.2f}%",
        })

    # Generate and print the report
    results_df = pd.DataFrame(results)
    print(results_df.to_string(index=False))
    
    # Calculate overall script accuracy across all numbers
    total_comparisons = results_df["Count"].sum()
    total_within_tol = sum((float(pct.strip('%')) / 100) * count for pct, count in zip(results_df[label], results_df["Count"]))

    if total_comparisons > 0:
        overall_precision = (total_within_tol / total_comparisons) * 100
        print(f"\n=======================================================")
        print(f"OVERALL SCRIPT ACCURACY: {overall_precision:.2f}%")
        print(f"=======================================================\n")

    return results_df

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate accuracy of the moo.py script against Praat outputs.")

    parser.add_argument("-orig", "--original", required=True, help="Path to the original Excel or CSV file.")
    parser.add_argument("-new", "--new", required=True, help="Path to the new CSV generated by moo.py.")
    parser.add_argument("-t", "--tolerance", type=float, default=0.005, help="Absolute tolerance in output units (default: 0.005).")
    parser.add_argument("-r", "--rel-tolerance", type=float, default=0.0,
                        help="Relative tolerance as a fraction of the reference value "
                             "(e.g. 0.01 = within 1%%). Scale-fair across F0 and formant "
                             "columns; a value passes if within the absolute OR relative "
                             "tolerance. Default 0 (absolute only).")
    parser.add_argument("-o", "--output", help="Optional path to save this accuracy report as a CSV.")

    args = parser.parse_args()

    report = compare_outputs(args.original, args.new, args.tolerance, args.rel_tolerance)

    if args.output and report is not None:
        report.to_csv(args.output, index=False)
        print(f"Precision report successfully saved to '{args.output}'")