import argparse
import pandas as pd
import numpy as np

def compare_outputs(original_path, new_path, tolerance):
    # Load the datasets
    print(f"Loading original file: {original_path}")
    if original_path.lower().endswith(('.xlsx', '.xls')):
        df_orig = pd.read_excel(original_path)
    else:
        df_orig = pd.read_csv(original_path)
        
    print(f"Loading new output file: {new_path}")
    df_new = pd.read_csv(new_path)

    # Standardize the file name column (handles "file", "File name", "File_Name", etc.)
    orig_file_col = next((col for col in df_orig.columns if col.lower() in ['file', 'file name', 'file_name']), df_orig.columns[0])
    new_file_col = next((col for col in df_new.columns if col.lower() in ['file', 'file name', 'file_name']), df_new.columns[0])

    # Merge the two dataframes on the filename
    merged = pd.merge(df_orig, df_new, left_on=orig_file_col, right_on=new_file_col, suffixes=('_orig', '_new'))

    if merged.empty:
        print("Error: No matching file names found between the two datasets. Check your file name formatting.")
        return

    # Identify matching columns to compare
    cols_orig = set(df_orig.columns) - {orig_file_col}
    cols_new = set(df_new.columns) - {new_file_col}
    common_cols = cols_orig.intersection(cols_new)

    print(f"\n--- Comparing {len(common_cols)} common columns across {len(merged)} matching files ---\n")

    results = []

    for col in sorted(common_cols):
        # Convert columns to numeric, coercing strings/errors to NaN
        s_orig = pd.to_numeric(merged[f"{col}_orig"], errors='coerce')
        s_new = pd.to_numeric(merged[f"{col}_new"], errors='coerce')

        # Drop NaNs to ensure we only compare valid numbers
        valid_mask = s_orig.notna() & s_new.notna()
        s_orig_valid = s_orig[valid_mask]
        s_new_valid = s_new[valid_mask]

        n_comparisons = len(s_orig_valid)

        # Skip column if no numeric data matches
        if n_comparisons == 0:
            continue

        # Calculate error metrics
        diff = np.abs(s_orig_valid - s_new_valid)
        mae = np.mean(diff)
        max_diff = np.max(diff)

        # Calculate precision based on the tolerance threshold
        within_tol = np.sum(diff <= tolerance)
        precision_pct = (within_tol / n_comparisons) * 100

        results.append({
            "Column": col,
            "Count": n_comparisons,
            "Mean_Abs_Error": f"{mae:.4f}",
            "Max_Difference": f"{max_diff:.4f}",
            f"Precision (tol<={tolerance})": f"{precision_pct:.2f}%"
        })

    # Generate and print the report
    results_df = pd.DataFrame(results)
    print(results_df.to_string(index=False))
    
    # Calculate overall script accuracy across all numbers
    total_comparisons = results_df["Count"].sum()
    total_within_tol = sum((float(pct.strip('%')) / 100) * count for pct, count in zip(results_df[f"Precision (tol<={tolerance})"], results_df["Count"]))
    
    if total_comparisons > 0:
        overall_precision = (total_within_tol / total_comparisons) * 100
        print(f"\n=======================================================")
        print(f"OVERALL SCRIPT PRECISION: {overall_precision:.2f}%")
        print(f"=======================================================\n")

    return results_df

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate precision of the moo.py script against Praat outputs.")
    
    parser.add_argument("-orig", "--original", required=True, help="Path to the original Excel or CSV file.")
    parser.add_argument("-new", "--new", required=True, help="Path to the new CSV generated by moo.py.")
    parser.add_argument("-t", "--tolerance", type=float, default=0.005, help="Tolerance for matching float variances (default: 0.005).")
    parser.add_argument("-o", "--output", help="Optional path to save this precision report as a CSV.")

    args = parser.parse_args()

    report = compare_outputs(args.original, args.new, args.tolerance)

    if args.output and report is not None:
        report.to_csv(args.output, index=False)
        print(f"Precision report successfully saved to '{args.output}'")